wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0301.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0302.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0303.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0304.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0305.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0306.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0307.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0308.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0309.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0310.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0311.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0312.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0401.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0402.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0403.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0404.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0405.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0406.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0407.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0408.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0409.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0410.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0411.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0412.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0501.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0502.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0503.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0504.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0505.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0506.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0507.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0508.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0509.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0510.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0511.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0512.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0601.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0602.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0603.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0604.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0605.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0606.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0607.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0608.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0609.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0610.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0611.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0612.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0701.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0702.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0703.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0704.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0705.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0706.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0707.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0708.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0709.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0710.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0711.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0712.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0801.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0802.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0803.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0804.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0805.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0806.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0807.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0808.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0809.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0810.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0811.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0812.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0901.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0902.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0903.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0904.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0905.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0906.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0907.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0908.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0909.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0910.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0911.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma0912.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1001.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1002.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1003.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1004.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1005.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1006.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1007.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1008.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1009.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1010.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1011.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1012.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1101.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1102.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1103.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1104.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1105.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1106.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1107.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1108.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1109.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1110.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1111.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1112.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1201.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1202.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1203.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1204.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1205.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1206.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1207.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1208.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1209.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1210.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1211.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1212.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1301.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1302.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1303.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1304.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1305.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1306.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1307.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1308.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1309.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1310.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1311.zip
wget http://earlywarning.usgs.gov/ftp2/global/eta/ma1312.zip
